export const searchedSkillsList: string[] = [
  "ReactJS",
  "ReactNative",
  "JavaScript",
  "Java",
  "Python",
  "Communication",
  "Pack Office",
  "Excel",
  "Power BI",
  "Machine Learning",
  "Gestion",
  "Gestion de recrutment",
  "Management",
  "RH",
  "Gepec",
];
export const moroccanCitiesList: string[] = [
  "Casablanca",
  "Rabat",
  "Fès",
  "Tanger",
  "Marrakech",
  "Meknès",
  "Salé",
  "Oujda",
  "Agadir",
  "Tétouan",
  "Safi",
  "Kénitra",
  "Settat",
  "Taza",
  "Ouarzazate",
  "El Jadida",
  "Tiznit",
  "Sidi Kacem",
  "Skhirate-Témara",
  "Sidi Slimane",
  "Sidi Ifni",
  "Sidi Bennour",
  "Sidi Bouzid",
  "Sidi Kacem",
  "Sidi Youssef Ben Ali",
  "Sidi Bou Said",
  "Sidi Bouzid",
  "Sidi Bou Said",
];
